version: 0.0
os: linux
files:
  - source: /
    destination: /usr/src/app # デプロイの前に /usr/src/app を作成しておく
hooks:
  BeforeInstall:
    - location: /aws/scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: /aws/scripts/install_python_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /aws/scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /aws/scripts/stop_server
      timeout: 300
      runas: root

