#!/bin/bash
apt-get install -y python3-pip
# https://docs.opencv.org/4.x/d2/de6/tutorial_py_setup_in_ubuntu.htmlk
apt-get install python3-opencv

# need to install streamlit with sudo since application is run with sudo
cd /usr/src/app || exit
pip3 install -r requirements.txt
